name: Deploy Azure Function project

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Api/src/Messenger.AzureFunctions/**"
      - ".github/workflows/**-azure-functions.yml"

env:
  AZURE_FUNCTIONAPP_NAME: 'messengerm-functions'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Api/functions/publish'
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish Project with zip
      shell: bash
      run: |
        dotnet publish ./Api/src/Messenger.AzureFunctions/Messenger.AzureFunctions.csproj -c Release -o '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        zip -r "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/function.zip" "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/*"

    - name: Deploy via Azure CLI
      run: |
        az functionapp deployment source config-zip \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --src "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/function.zip"
